ALTER TABLE orders ADD COLUMN IF NOT EXISTS buyer_phone TEXT NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS buyer_message TEXT NOT NULL DEFAULT '';

ALTER TABLE artisans ADD COLUMN IF NOT EXISTS phone TEXT NOT NULL DEFAULT '';
